name: fc
description: A CLI tool to generate a Flutter project with a clean architecture.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  args: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  project-generator:
    path: bin/main.dart
